IS2_SGP/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls,name='home'),
    url(r'', include('login.urls')),

]

gestionarFlujos/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import gestionarproyecto
from  gestionarFlujos import views

app_name = 'gestionarflujos'

urlpatterns = [

    url(r'^agregar/', views.CreaFlujosView.as_view(), name='crearflujos'),
    url(r'^(?P<detailflujos_url>\w+)$', views.FlujosDetailView.as_view(), name='detailtflujos'),
    url(r'^estados/(?P<detailflujos_url>\w+)/(?P<detailestado_url>\w+)$', views.EstadoDetailView.as_view(), name='detailestado'),

]

login/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.context_processors import auth
from django.contrib.auth import  views as auth_views
import gestionarproyecto
from . import views
import gestionarus
urlpatterns = [
    url(r'^$', views.hacer_login, name='login'),
    url(r'^logout$',views.hacer_logout,name='logout_url'),
    url(r'^usuario/(?P<usuario_nombre>[\w-]+)/', include('gestionarproyecto.urls')),
    url(r'^usuario/(?P<usuario_nombre>[\w-]+)/',include('gestionarroles.urls')),
    url(r'^home/(?P<usuario_nombre>[\w-]+)/', views.mostrar_interfaz,name='index'),
    url(r'^usuario/(?P<usuario_nombre>[\w-]+)/gestionarusuarios/',include('gestionarusuarios.urls')),
    url(r'^gestionarinformacion/',include('gestionarinformacion.urls'))
]

tiposUS/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from tiposUS import  views


app_name = 'tiposUS'

urlpatterns = [
    url(r'^agregarv2/', views.CreaTypeUSView.as_view(), name='creartiposusv2'),
    url(r'^listadotiposus/', views.listar_typeUS, name='listadotiposus'),
    url(r'^editar/(?P<detailtipous_url>\w+)$', views.EditTypeUSView.as_view(), name='updatetipous')
    ]

tiposUS/models.py
from django.db import models
from gestionarFlujos.models import Flujo
from gestionarproyecto.models import  Proyectos
from django.contrib.postgres.fields import ArrayField
# Se crear el modelo de datos tipo de US con los atributos

class gestiontipoUS(models.Model):
    nombretipus=models.CharField(max_length=100,blank=False)
    flujo =  models.CharField(max_length=100)
    proyecto = models.ForeignKey(Proyectos, on_delete=False, blank=False)
    estado = ArrayField(models.CharField(max_length=100, editable=False, unique=True))
    subestado = ArrayField(models.CharField(max_length=100, editable=False, unique=True), default='Hacer,Haciendo,Hecho')

    class Meta:
        db_table = 'gestiontipous'
        unique_together = ('nombretipus','proyecto'),('estado','proyecto')

    def __str__(self):
        return u'{0}'.format(self.nombretipus,self.estado,self.proyecto)

tiposUS/forms.py
from typing import Dict

from django import forms
from django.core.exceptions import NON_FIELD_ERRORS

from gestionarproyecto.models import Proyectos
from tiposUS.models import gestiontipoUS
from django.db.models import Q
from gestionarFlujos.models import Flujo

class CreatetypeUSForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreatetypeUSForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        self.fields['subestado'].widget.attrs['readonly']='readonly'

    class Meta:
        model = gestiontipoUS
        fields = ['nombretipus', 'flujo', 'estado', 'subestado', 'proyecto']
        help_texts = {
            'estado': 'Estado1,Estado2,Estado3'
        }
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(field_labels)s no se pueden repetir",
            }
        }

tiposUS/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView,UpdateView
from django.views.generic.detail import DetailView

from tiposUS.models import gestiontipoUS
from gestionarFlujos.models import Estado
from tiposUS.forms import CreatetypeUSForm


from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.urls import reverse
from gestionarproyecto.models import  *
from django.shortcuts import get_object_or_404

def listar_typeUS(request,usuario_nombre,proyecto_nombre_url):
    objetoproyectoactual = Proyectos.objects.get(nombreproyecto=proyecto_nombre_url)
    objeto_tipo_us = gestiontipoUS.objects.filter(proyecto=objetoproyectoactual)
    return render(request,'mostrartiposUS.html',{  "objeto_tipo_us":objeto_tipo_us,'proyecto_nombre_url':proyecto_nombre_url,"username":usuario_nombre})


#Vista para mostrar el formulario y guardar un tipoUS

class CreaTypeUSView(CreateView):
    template_name = 'addTypeUS.html'
    model = gestiontipoUS
    form_class = CreatetypeUSForm
    #se valida el formulario
    def form_valid(self, form,**kwargs):
        #se trae el objeto Flujo del formulario
        Objectypetus=form.save(commit=False)
        #se enlaza el flujo objeto a un proyecto
        Objectypetus.proyecto = get_object_or_404(Proyectos, nombreproyecto=self.kwargs.get('proyecto_nombre_url'))
        # se guarda el objeto flujo
        Objectypetus.save()

        return  HttpResponseRedirect(reverse('visualizarproyecto',kwargs={'proyecto_nombre_url':self.kwargs.get('proyecto_nombre_url'),'usuario_nombre':self.request.user.username}))


class EditTypeUSView(UpdateView):
    template_name='editTypeUS.html'
    model = gestiontipoUS
    success_url = reverse_lazy('courses:list')
    form_class = CreatetypeUSForm

    def get_object(self,**kwargs):
        objproyecto = get_object_or_404(Proyectos, nombreproyecto=self.kwargs.get('proyecto_nombre_url'))
        return gestiontipoUS.objects.get(nombretipus=self.kwargs.get('detailtipous_url'),proyecto=objproyecto)





    def form_valid(self, form,**kwargs):
        obje=form.save(commit=False)
        obje.proyecto=get_object_or_404(Proyectos, nombreproyecto=self.kwargs.get('proyecto_nombre_url'))
        #se guarda en la base de datos
        obje.save()
        #se muestra el tipous creado en la plantilla
        return HttpResponseRedirect(reverse('tiposUS:detailtiposus', kwargs={'proyecto_nombre_url':obje.proyecto,'detailtipous_url': form.cleaned_data['nombre'], 'usuario_nombre' : self.kwargs.get('usuario_nombre')},current_app='tiposUS'))

tiposUS/templates/ListtypeUS.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Listado de Tipos de US</title>
</head>
<body>

    {% block content %}
        {% include 'login/logeado.html' %}
                        <h4 class="page-header" style="text-align: center">Lista de Tipos de US asociados al proyecto</h4>
                <h5 class="page-header" style="text-align: center">Seleccione un Tipo de US asociado al proyecto(<a href="{% url 'tiposUS:creartiposus' username objetoproyecto.nombreproyecto %}?usuario={{ username }}">Crear Tipo US</a>)</h5>
                 <div class="container-fluid" style="width: 90%">
                 <ul class="list-group">

                {% for i in objeto_tipo_us %}
                    <li class="list-group-item">
                        <a href="{% url 'tiposUS:detailtiposus' username objetoproyecto.nombreproyecto i.nombre %}?usuario={{ username }}">{{ i }}</a>
                    </li>

                {% endfor %}
                 </ul>
    {% endblock %}

</body>
</html>

tiposUS/templates/addTypeUS.html
{% include "login/logeado.html"  %}

{% block content %}
    <div class="container" style="width: 90%">
<a class="btn alert-danger" href="javascript:history.go(-1)"> < Atrás</a>
      <h4 class="page-header" style="text-align: center">Crear Tipo de US</h4>

        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="guardar" class="btn btn-default"/>
        </form>


       </div>


{% endblock %}

tiposUS/templates/addtiposUS.html
{% include "login/logeado.html"  %}

    {% block content %}
    <div class="container" style="width: 90%">


      <h4 class="page-header" style="text-align: center">Crear Tipo de US</h4>

        <form method="post">
            {% csrf_token %}
             {% for i in form %}
                 {% if i.name == "flujo" %}
                       <label for="{{ i.name }}">{{ i.name }} : <a href="{% url 'gestionarflujos:crearflujos' username proyecto.nombreproyecto %}?usuario={{ username }}">Crear Flujo</a> </label>
                {{ i }}
                 {% else %}
                      <label for="{{ i.name }}">{{ i.name }}</label>
                    {{ i }}
                 {% endif %}


            {% endfor %}

            <br>
            <input type="submit" value="guardar" class="btn btn-default"/>
        </form>

    </div>


     {% endblock %}

tiposUS/templates/detailsTypeUS.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

tiposUS/templates/detailtipoUS.html
{% include "login/logeado.html"  %}

    {% block content %}


            <div class="form-group">
                <label> Type User History:</label>
                <p>{{ tipous.nombre}}</p>
             </div>

            <div class="form-group">
                <label > Flujo: {{ tipous.flujo }} </label>
          </div>



             <div class="form-group">

              Estados<a href=" {% url 'gestionarflujos:agregarestado' username proyecto.nombreproyecto tipous.flujo   %}?usuario={{ username }} ">Agregar Estado</a>
        </div>

        {% for e in estado %}

                <div class="form-group">
                <label > Estado: {{e.estado}} </label>
                  </div>


                <div class="form-group">
                <label > Sub Estados  </label>
             </div>
            {% for se in e.subestado %}

                   <p>{{se}}</p>

         {% endfor %}
     {% endfor %}




    {% endblock %}

tiposUS/templates/editTypeUS.html
{% include "login/logeado.html"  %}

    {% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

tiposUS/templates/mostrartiposUS.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Listado de Tipos de US</title>
</head>
<body>

    {% block content %}
        {% include 'login/logeado.html' %}
        <div class="container-fluid" style="width: 90%">
        <a class="btn alert-danger" href="javascript:history.go(-1)"> < Atrás</a>
    <h4 class="page-header" style="text-align: center">Lista de Tipos de US</h4>
        <h5 class="page-header" style="text-align: center"><a class="btn btn-info" href="{% url 'tiposUS:creartiposusv2'  user proyecto_nombre_url  %}">Crear Tipo de US</a> </h5>
                 <ul class="list-group">

                {% for i in objeto_tipo_us %}
                    <li class="list-group-item" class="proyecto">{{ i }}</li>
                    <div class="alert alert-info" style="display: none; margin: 0">
                            <p>tipoUS : {{ i.nombretipus}} </p>
                            <p>Flujo : {{ i.flujo}} </p>
                            <p>Estado : {{ i.estado}} </p>
                            <p>Subestado : {{ i.subestado}} </p>
                    </div>
                {% endfor %}
                 </ul>
        </div>





         <script>
                $(".list-group-item").click(function(){
                    $(this).next().slideToggle('slow')
                })
        </script>


    {% endblock %}




</body>
</html>